# -*- coding: utf-8 -*-
"""Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqgyHUCJsAl5_mFnqCSBKEKkL1R2puCS

Calculator using Python

Here's a basic Python calculator function that can perform addition, subtraction, multiplication, and division. You can call this function with two numbers and an operator as a string.
"""

def Calculator(num1, num2, operator):
  if operator== "+":
    return num1+num2
  elif operator=="-":
    return num1-num2
  elif operator =="*":
    return num1*num2
  elif operator =="/":
    if num2==0:
      return"Error"
    return num1/num2
  else:
    return "Invalid Input "

num1=float(input("Enter the first number:"))
num2=float(input("Enter the second number:"))
operator=input("Enter the operator (+,-,*,/)")

result=Calculator(num1,num2,operator)

print(result)